// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IntegrationServices.Models;

public partial class AnniFatture
{
    public int Anno { get; set; }
}