// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IntegrationServices.Models;

public partial class ListaFatture
{
    public int Id { get; set; }

    public string PercorsoFile { get; set; }

    public string FileNameHash { get; set; }

    public DateTime UltimaDataAggiornamento { get; set; }
}