// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace IntegrationServices.Models;

public partial class NiFiTestContext : DbContext
{
    public NiFiTestContext(DbContextOptions<NiFiTestContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AnniFatture> AnniFatture { get; set; }

    public virtual DbSet<ListaFatture> ListaFatture { get; set; }

    public virtual DbSet<Servizi> Servizi { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AnniFatture>(entity =>
        {
            entity.HasKey(e => e.Anno).HasName("PK__AnniFatt__05AC5A8C8AA502E4");

            entity.Property(e => e.Anno).ValueGeneratedNever();
        });

        modelBuilder.Entity<ListaFatture>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ListaFat__3213E83F7649640B");

            entity.HasIndex(e => e.FileNameHash, "UK_ListaFatture").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.FileNameHash)
                .IsRequired()
                .HasMaxLength(40)
                .IsUnicode(false);
            entity.Property(e => e.PercorsoFile)
                .IsRequired()
                .HasMaxLength(2048);
        });

        modelBuilder.Entity<Servizi>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Host)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("host");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("password");
            entity.Property(e => e.Servizio)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("servizio");
            entity.Property(e => e.Utente)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("utente");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}