// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IntegrationServices.Models;

public partial class Servizi
{
    public int Id { get; set; }

    public string Servizio { get; set; }

    public string Host { get; set; }

    public string Utente { get; set; }

    public string Password { get; set; }

    public int? Porta { get; set; }
}